# Generated by Django 4.0.5 on 2023-02-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Эконом, Стандарт, VIP', max_length=20, verbose_name='Наименование тарифа')),
                ('description', models.TextField(verbose_name='Описание тарифа')),
                ('price', models.IntegerField(verbose_name='Стоимость тарифа')),
            ],
        ),
    ]
