# Generated by Django 4.0.5 on 2023-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_bot', '0004_alter_customer_options_alter_tariff_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_subs',
            field=models.BooleanField(default=False, verbose_name='Наличие подписки'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Никнейм в телеграме'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название заказа'),
        ),
    ]
