# Generated by Django 4.0.5 on 2023-02-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_bot', '0006_remove_customer_is_subs_customer_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_orders', to='freelance_bot.customer', verbose_name='Исполнитель'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(db_index=True, verbose_name='ID чата')),
                ('message', models.TextField(verbose_name='Содержание сообщения')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_messages', to='freelance_bot.customer', verbose_name='Заказчик')),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_messagess', to='freelance_bot.customer', verbose_name='Исполнитель')),
            ],
        ),
    ]
