# Generated by Django 3.2 on 2023-02-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_bot', '0012_message_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='message',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='message',
            name='message_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_messages', to='freelance_bot.customer', verbose_name='От кого'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_messagess', to='freelance_bot.customer', verbose_name='Kому'),
        ),
    ]
